### ISSUE TITLE
Exception when registering SparkListener

### ISSUE THREAD

**Issue by dciangot** [itsjafer/jupyterlab-sparkmonitor#15]
Hi,

I'm giving a try to this interesting extension, but I'm failing to initialize the SparkContext ( * ). I'm wondering if you have any idea to debug this ( ** ). Do you have any idea why it still don't find the proper class? I have just followed the instructions here for the installation ( *** )

Thanks in advance.

(*)
from pyspark.sql import SparkSession
spark = SparkSession.builder\
        .config('spark.extraListeners', 'sparkmonitor.listener.JupyterSparkMonitorListener')\
        .config('spark.driver.extraClassPath', '/usr/local/spark/jars/listener.jar')\
        .getOrCreate()

(**)
Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Exception when registering SparkListener
	at org.apache.spark.SparkContext.setupAndStartListenerBus(SparkContext.scala:2398)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:555)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: sparkmonitor.listener.JupyterSparkMonitorListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
	at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2682)
	at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2680)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2680)
	at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2387)
	at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2386)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.SparkContext.setupAndStartListenerBus(SparkContext.scala:2386)
	... 13 more

(***)
https://github.com/itsjafer/jupyterlab-sparkmonitor#setting-up-the-extension

**Comment by itsjafer** [comment]
Hi!

In regards to this line: `.config('spark.driver.extraClassPath', '/usr/local/spark/jars/listener.jar')`

Did you place the listener.jar from the python package into that path? i.e. is listener.jar in that file path? Try opening a terminal from within jupyterlab and checking if the jar is there.

If it's not, you can do two things:

1. Set the value of spark.driver.extraClassPath to wherever your python packages are being installed. For example, in my case this might be: `venv/lib/python3.7/site-packages/sparkmonitor/listener.jar`
2. Move the aforementioned listener.jar to the path you listed above


If it is, based on that error, it seems that the kernel extension is loading in so you probably have a conf variable defined.

Try running the following cell and reporting back the value of `spark.driver.extraClassPath`:

```
import pyspark
print(conf.toDebugString())
```

conf is a variable that the kernel extension will register once you import pyspark

**Comment by dciangot** [comment]
thanks a lot, this is solved now. It was indeed a firewall problem, strange enough :/
