### ISSUE TITLE
jupyterlab_sparkmonitor is not a valid npm package errore

### ISSUE THREAD

**Issue by dciangot** [itsjafer/jupyterlab-sparkmonitor#17]
While trying to load jupyterlab extension manager I'm getting this error (*)
Do you have any clue?

(*)
```
SPARKMONITOR_SERVER: Loading Server Extension
[E 08:43:41.398 NotebookApp] Uncaught exception GET /lab/api/extensions?1589273014548 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/extensions?1589273014548', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 92, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 92, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 161, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 161, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 195, in _load_outdated
        app_options=self.app_options
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 550, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1675, in latest_compatible_package_versions
        raise ValueError(msg % keys)
    ValueError: "['@jupyter-widgets/jupyterlab-manager@1.1.0', 'jupyterlab_sparkmonitor@1.1.0']" is not a valid npm package
```

**Comment by uday1889** [comment]
Do you know what version of nodejs you're using? Updating `nodejs` `npm` helped fixed this issue for me in the past. The following thread may help:
https://github.com/jupyter-widgets/ipywidgets/issues/1982

**Comment by itsjafer** [comment]
Please try again with version 3.0.1 and report back if this issue persists
